name : CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


  jobs:y
    test:
      runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Test app
        run: test -f app.txt
